# Generated by Django 2.0.5 on 2018-11-01 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='teams',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Event'),
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.Profile'),
        ),
    ]
