# Generated by Django 2.1.3 on 2018-11-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20181102_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='members',
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='portal.Profile'),
        ),
    ]
