# Generated by Django 2.1.3 on 2018-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20181103_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='portal.Profile'),
        ),
    ]
