# Generated by Django 2.0.5 on 2018-10-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=100)),
                ('start_date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('end_date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('start_time', models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>')),
                ('end_time', models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participant', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending', to='portal.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Clubs'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='joint_secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_sec', to='portal.Profile'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='portal.Profile'),
        ),
    ]
